
spring:
  cloud:
    function:
      definition: topicTwo;topicThree
    stream:
      bindings:
        topicTwo-in-0:
          destination: topic-two
        topicThree-out-0:
          destination: topic-three